// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace NathansWay.iOS.Numeracy
{
	public partial class vNumberCombo : UIView
	{
		public vNumberCombo (IntPtr handle) : base (handle)
		{
		}
	}
}
