// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace NathansWay
{
	public partial class CustomSlideSegue : UIStoryboardSegue
	{
		public CustomSlideSegue (IntPtr handle) : base (handle)
		{
		}
	}
}
